---
# Service，将Consul集群的端口暴露给K8S的其他Pod
apiVersion: v1
kind: Service
metadata:
  namespace: consul
  name: consul
  labels:
    name: consul
spec:
  type: NodePort
  ports:
    - name: http
      port: 8500
      targetPort: 8500
      nodePort: 31500
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 31443
    - name: rpc
      port: 8400
      targetPort: 8400
      nodePort: 31400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
      nodePort: 31301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
      nodePort: 31301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
      nodePort: 31302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
      nodePort: 31302
    - name: server
      port: 8300
      targetPort: 8300
      nodePort: 31300
    - name: consuldns
      port: 8600
      targetPort: 8600
      nodePort: 31600
  selector:
    app: consul